# File: netlify.toml

[build]
  # This is the command to build your Next.js site
  command = "npm run build"
  
  # This tells Netlify that your final website is in the .next folder
  publish = ".next"

[functions]
  # This explicitly tells Netlify to look for your functions here
  directory = "netlify/functions"